run:
  timeout: 120s
  tests: true


linters:
  enable:
    - goimports
    - errcheck
    - gofmt
    - errorlint
    - gocritic
    - gocyclo
    - gocognit
    - revive
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - nakedret
    - wsl

linters-settings:
  revive:
    severity: warning
    confidence: 0.3
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: get-return
      - name: early-return
      - name: identical-branches
      - name: defer
        arguments:
          - - loop
            - method-call
            - return
      - name: string-of-int
      - name: waitgroup-by-value
      - name: range-val-address
      - name: argument-limit
        arguments:
          - 10
      - name: atomic
      - name: bool-literal-in-expr
      - name: deep-exit
      - name: function-result-limit
        arguments:
          - 5
      - name: modifies-value-receiver
      - name: unnecessary-stmt
  gocyclo:
    min-complexity: 9
  gocognit:
    min-complexity: 10
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - ifElseChain
      - unnecessaryBlock
      - sprintfQuotedString
      - deferUnlambda
      - paramTypeCombine
      - builtinShadow
      - octalLiteral
      - rangeValCopy
      - nestingReduce
      - httpNoBody
      - regexpSimplify
      - externalErrorReassign
      - hugeParam
      - importShadow
      - unnamedResult
      - filepathJoin
      - commentedOutCode
  wsl:
    allow-assign-and-anything: true
    allow-assign-and-call: true
    allow-cuddle-declarations: true
    force-err-cuddling: true
  gosec:
    excludes:
      - "G115"
  staticcheck:
    checks:
      - all
      - -QF1008
  errcheck:
    check-type-assertions: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: autogenerated\.go$
      linters:
        - gocyclo
        - gocognit