services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - REDIS_ADDR=redis:6379
      - LOCAL_DEV=true
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
